### ISSUE TITLE
Latest container issue will not start

### ISSUE THREAD

**Issue by dwesthead** [3x3cut0r/docker#15]
Hi,
After pulling the "latest" version of the PrivateGPT container, the container just restarts every few seconds and doesnt stay running.

I can also see a traceback and numerous failed lines in the logs that are also repeated for every restart.

It is the same host that is running the container image from January this year .... are there any updates that are needed to the host for this current version to work ?

I have tried to build the container from the dockerfile too. It builds with no errors but has the same problem starting the container from the image.

Thanks.
Dean.

**Comment by dwesthead** [comment]
If it helps, the logs show this repeated for every restart :

privategpt version: 0.5.0
18:56:45.754 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/worker/app/private_gpt/main.py", line 4, in <module>
    from private_gpt.launcher import create_app
  File "/home/worker/app/private_gpt/launcher.py", line 8, in <module>
    from llama_index.core.callbacks import CallbackManager
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 8, in <module>
    from llama_index.core.base.base_retriever import BaseRetriever
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/base/base_retriever.py", line 29, in <module>
    from llama_index.core.service_context import ServiceContext
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/service_context.py", line 11, in <module>
    from llama_index.core.indices.prompt_helper import PromptHelper
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/prompt_helper.py", line 20, in <module>
    from llama_index.core.node_parser.text.token import TokenTextSplitter
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/node_parser/__init__.py", line 12, in <module>
    from llama_index.core.node_parser.relational.hierarchical import (
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/node_parser/relational/__init__.py", line 4, in <module>
    from llama_index.core.node_parser.relational.markdown_element import (
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/core/node_parser/relational/markdown_element.py", line 4, in <module>
    import pandas as pd
  File "/home/worker/app/.venv/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/worker/app/.venv/lib/python3.11/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/worker/app/.venv/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

And it restarts every 60 seconds.

Dean.

**Comment by 3x3cut0r** [comment]
i think that is an upstream issue atm.
something wrong with the numpy package.
see [here](https://github.com/zylon-ai/private-gpt/issues/1979)

i am currently on vacation.
i can maybe fix this in 2 weeks.

try running an older version instead. sry for that :/

**Comment by dwesthead** [comment]
Hi,

Thanks for replying even on vacation !

After reading that article you linked to, i have changed your dockerfile for the latest version so that it installs numpy 1.26.0 and now it all builds and starts up as it should !

Thanks for your help with this !

Do you know if this latest PrivateGPT of yours includes the auto consumption of documents ? If the container gets restarted i need to re upload the docs at the moment.

Have a great vacation and i am sure we will be in contact in a couple of weeks when you are back.

Thanks.
Dean.

**Comment by 3x3cut0r** [comment]
if 'KEEP_FILES' is 'true', which should be the default, the files should be available even after restart.

**Comment by arvindnagartectum** [comment]
Hello,
I have pulled the latest version of docker, but showing the error and getting existed.

Here is the error:

20:15:08.578 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/worker/app/private_gpt/main.py", line 3, in <module>
    from private_gpt.di import global_injector
  File "/home/worker/app/private_gpt/di.py", line 3, in <module>
    from private_gpt.settings.settings import Settings, unsafe_typed_settings
  File "/home/worker/app/private_gpt/settings/settings.py", line 472, in <module>
    unsafe_typed_settings = Settings(**unsafe_settings)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
gemini
  Field required [type=missing, input_value={'server': {'env_name': '..., 'llm_model': 'gpt-4'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by 3x3cut0r** [comment]
i implemented gemini and clickhouse support.
could you try it again?
