### ISSUE TITLE
Problem while running docker

### ISSUE THREAD

**Issue by rajkiranjeet** [3x3cut0r/docker#17]
2024-08-04 15:32:36 10:02:36.913 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
2024-08-04 15:32:36 Traceback (most recent call last):
2024-08-04 15:32:36   File "<frozen runpy>", line 198, in _run_module_as_main
2024-08-04 15:32:36   File "<frozen runpy>", line 88, in _run_code
2024-08-04 15:32:36   File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
2024-08-04 15:32:36     from private_gpt.main import app
2024-08-04 15:32:36   File "/home/worker/app/private_gpt/main.py", line 3, in <module>
2024-08-04 15:32:36     from private_gpt.di import global_injector
2024-08-04 15:32:36   File "/home/worker/app/private_gpt/di.py", line 3, in <module>
2024-08-04 15:32:36     from private_gpt.settings.settings import Settings, unsafe_typed_settings
2024-08-04 15:32:36   File "/home/worker/app/private_gpt/settings/settings.py", line 614, in <module>
2024-08-04 15:32:36     unsafe_typed_settings = Settings(**unsafe_settings)
2024-08-04 15:32:36                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-04 15:32:36   File "/home/worker/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 193, in __init__
2024-08-04 15:32:36     self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-08-04 15:32:36 pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
2024-08-04 15:32:36 summarize
2024-08-04 15:32:36   Field required [type=missing, input_value={'server': {'env_name': '..., 'llm_model': 'gpt-4'}}, input_type=dict]
2024-08-04 15:32:36     For further information visit https://errors.pydantic.dev/2.8/v/missing
2024-08-04 15:32:35 privategpt version: 0.6.0

please provide solution

**Comment by 3x3cut0r** [comment]
should work now. please try
